default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: todo-backend_development

test:
  <<: *default
  host: localhost
  port: 5432
  database: todo-backend_test
  username: postgres
  password: ''
